#!/bin/bash
# Quiz4Win — commit & push the strict-elimination + survivors-only payout work.
# Generated by A-01 (Primary Builder). Safe to delete after the push succeeds.
set -euo pipefail

cd "$(dirname "$0")"

git add \
  deploy/game-orchestrator/orchestrator.ts \
  supabase/migrations/20260605200000_compute_game_ranks_exclude_eliminated.sql \
  project-brain/Change_Log_AI.md

git commit -m "[DOMAIN] No-answer = wrong-answer; prize pool restricted to survivors

Implements the spec: 'not answering a question must be treated exactly
the same as answering incorrectly' and 'the prize pool is always
distributed only among the players who remain in the game until the end
and successfully survive all elimination rules.'

orchestrator.ts:
- New applyElimination() helper: sRem from K.parts(gameId) so eliminated
  users no longer reappear in every subsequent SDIFF notAnswered round;
  PATCH game_participants with participant_role='eliminated', eliminated,
  eliminated_at, elimination_reason, wrong_count, lives_remaining;
  broadcast USER_ELIMINATED LiveKit DataChannel event.
- closeQuestion: no-answer is now identical to wrong-answer. Skips
  already-eliminated users in the notAnswered loop; bumps wrongCount /
  decrements remainingLives; calls applyElimination when threshold
  crossed (maxWrong=1 -> first miss eliminates; maxWrong=3 -> 4th miss
  eliminates); mirrors wrong_count/lives_remaining to Postgres on
  survivors. Now also emits noAnswerEliminatedCount in QUESTION_CLOSED.
- handlePersistAnswer: wrong-answer eliminations now mirror to Postgres
  + remove from Redis participants set + broadcast (previously the
  elimination lived only in Redis so compute_game_ranks still ranked
  them). Wrong answers now PATCH wrong_count/lives_remaining on
  game_participants.
- gameRoomNames Map cache + resolveRoomName helper populated by
  handleStartGame and recoverRunningGames, with a one-shot dbSelect
  fallback.

migration 20260605200000_compute_game_ranks_exclude_eliminated.sql:
- compute_game_ranks now RANK()s only over rows where role='player' AND
  participant_role='participant' AND eliminated=FALSE.
- Eliminated rows get rank=NULL and status='disqualified'.
- distribute_prizes unchanged: NULL BETWEEN ... is NULL, so eliminated
  players are naturally skipped by every prize tier.

R-11 frozen surfaces (getPublicClient, REDIS_URL expansion, .env byte
hygiene) untouched. No Edge Function or docker-compose changes."

git push origin main
