/**
 * LLM Question Engine for Quiz4Win Real-Time Quiz (§5).
 *
 * Calls OpenAI gpt-4o-mini to generate multilingual quiz questions with
 * stable option IDs (A/B/C/D) per §5.5 — the option ID never changes across
 * languages; only the displayed text changes.
 *
 * Output includes:
 *   - Canonical question identity (questionId generated by caller)
 *   - Four stable options [{id,text}] in canonical (English) form
 *   - correctOptionId (one of "A","B","C","D")
 *   - localizedPayloads keyed by language code
 *   - explanation, safety flags, estimated answer time
 *
 * Env vars (never logged — R-01):
 *   OPENAI_API_KEY — secret key
 *   OPENAI_MODEL   — defaults to "gpt-4o-mini"
 */

export interface QuestionOption {
  id: string;   // stable: "A" | "B" | "C" | "D"
  text: string; // display text in this language
}

export interface LocalizedPayload {
  language: string;
  questionText: string;
  options: QuestionOption[];
}

export interface GeneratedQuestion {
  canonicalText: string;
  options: QuestionOption[];        // English canonical options
  correctOptionId: string;          // "A" | "B" | "C" | "D"
  localizedPayloads: LocalizedPayload[];
  explanation: string;
  estimatedAnswerTimeSec: number;
  safetyFlags: string[];
  ambiguityFlags: string[];
}

export interface GenerateQuestionParams {
  topic?: string;
  category?: string;
  difficulty?: "easy" | "medium" | "hard";
  questionType?: string;
  targetLanguages: string[];        // e.g. ["en","ar","fa","tr","de"]
  audienceLevel?: string;
  regionOrCulture?: string;
  avoidTopics?: string[];
  timeLimitSeconds?: number;
  gameType?: string;
}

const SYSTEM_PROMPT = `You are a multilingual quiz question generator.
Rules:
- Generate exactly ONE question with FOUR options labelled A, B, C, D.
- Option IDs (A/B/C/D) must be IDENTICAL across all languages.
- Only one option is correct.
- Avoid: political manipulation, hate speech, sexual content, religious provocation,
  illegal instructions, ambiguous wording, multiple-correct-answer situations.
- Output ONLY valid JSON matching the schema below — no markdown fences.

Required JSON schema:
{
  "canonicalText": "string (English question text)",
  "options": [{"id":"A","text":"…"},{"id":"B","text":"…"},{"id":"C","text":"…"},{"id":"D","text":"…"}],
  "correctOptionId": "A"|"B"|"C"|"D",
  "localizedPayloads": [
    {"language":"en","questionText":"…","options":[{"id":"A","text":"…"},…]},
    …one entry per requested language…
  ],
  "explanation": "string",
  "estimatedAnswerTimeSec": number,
  "safetyFlags": [],
  "ambiguityFlags": []
}`;

export async function generateQuestion(
  params: GenerateQuestionParams,
): Promise<GeneratedQuestion> {
  const apiKey = Deno.env.get("OPENAI_API_KEY") ?? "";
  if (!apiKey) throw new Error("OPENAI_API_KEY not configured");

  const model = Deno.env.get("OPENAI_MODEL") ?? "gpt-4o-mini";

  const userPrompt = JSON.stringify({
    topic: params.topic ?? "general knowledge",
    category: params.category ?? "mixed",
    difficulty: params.difficulty ?? "medium",
    questionType: params.questionType ?? "factual",
    targetLanguages: params.targetLanguages,
    audienceLevel: params.audienceLevel ?? "general",
    regionOrCulture: params.regionOrCulture ?? "global",
    avoidTopics: params.avoidTopics ?? [],
    timeLimitSeconds: params.timeLimitSeconds ?? 10,
    gameType: params.gameType ?? "elimination",
  });

  const res = await fetch("https://api.openai.com/v1/chat/completions", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${apiKey}`,
    },
    body: JSON.stringify({
      model,
      temperature: 0.7,
      max_tokens: 1500,
      response_format: { type: "json_object" },
      messages: [
        { role: "system", content: SYSTEM_PROMPT },
        { role: "user", content: userPrompt },
      ],
    }),
  });

  if (!res.ok) {
    const txt = await res.text().catch(() => "");
    throw new Error(`OpenAI API error ${res.status}: ${txt.slice(0, 300)}`);
  }

  const json = await res.json() as {
    choices: Array<{ message: { content: string } }>;
  };
  const content = json.choices?.[0]?.message?.content;
  if (!content) throw new Error("OpenAI returned empty content");

  const parsed = JSON.parse(content) as GeneratedQuestion;

  // Validate mandatory fields
  if (!parsed.correctOptionId || !["A","B","C","D"].includes(parsed.correctOptionId)) {
    throw new Error("LLM returned invalid correctOptionId");
  }
  if (!Array.isArray(parsed.options) || parsed.options.length !== 4) {
    throw new Error("LLM returned wrong number of options");
  }

  return parsed;
}
